# Generated by Django 4.2.7 on 2023-12-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0053_remove_course_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='Email',
            field=models.EmailField(max_length=50),
        ),
    ]
